name: Auto-Label Issues
on:
    issues:
        types: [opened]

jobs:
    auto-label:
        runs-on: ubuntu-latest
        permissions:
            issues: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Parse Issue Form
              id: parse
              uses: stefanbuck/github-issue-parser@v3
              with:
                  template-path: .github/ISSUE_TEMPLATE/le_bug.yml

            - name: Add labels based on parsed form data
              uses: actions/github-script@v7
              env:
                  PARSED_DATA: ${{ steps.parse.outputs.jsonString }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN}}
                  script: |
                      const parsedData = JSON.parse(process.env.PARSED_DATA);

                      console.log('Parsed issue form data:', parsedData);

                      const labelsToAdd = [];

                      for (const mod of parsedData.le_mod) {
                        labelsToAdd.push(mod.toLowerCase().replace(/ /g, '-'));
                      }

                      if (labelsToAdd.length > 0) {
                        await github.rest.issues.addLabels({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: context.payload.issue.number,
                          labels: labelsToAdd
                        });

                        console.log('Added labels:', labelsToAdd);
                      } else {
                        console.log('No labels matched for this issue.');
                      }
